main: main.o practica3.hpp practica5.hpp practica6.hpp tad_texto.hpp tad_tren.hpp tad_texto.hpp tad_simbolo.hpp
	g++ main.cpp practica3.hpp practica5.hpp practica6.hpp tad_texto.hpp tad_tren.hpp tad_texto.hpp tad_simbolo.hpp -o main -lm
	./main

clean_win: 
	del *.gch
	del *.o 
	del *.exe